### ISSUE TITLE
Need these three files too

### ISSUE THREAD

**Issue by ZoinkCN** [Captain-Of-Coit/hookui#14]
![屏幕截图 2023-11-30 090110](https://github.com/Captain-Of-Coit/hookui/assets/43642083/f0961d18-71fc-47e4-ad95-a6a99bccca8d)

**Comment by Captain-Of-Coit** [comment]
Hm, could I have some more info about your OS, installed via Game Pass/Steam and so on? The more info the better.

It seems to work as-is for users right now, so not sure why you need these VS what others need...

**Comment by Captain-Of-Coit** [comment]
AFAIK, this is working as expected. If more people have issues with this, please open a new issue so we can get to the bottom of it.
