### ISSUE TITLE
Cannot create files in game directory? 

### ISSUE THREAD

**Issue by glitch-bee** [Captain-Of-Coit/hookui#21]
Here is the error: 

![image](https://github.com/Captain-Of-Coit/hookui/assets/152710390/fe4c54ae-ee14-4e78-97da-7c14139594b7)

computer info
i9-13900KF   3.00 GHz
64gb ram
4070Ti
Windows 11

I'm the only user on this computer. This seems to be the only mod (and anything that depends on it)  I am having issues with. I have tried manual and thunderstore installs.

**Comment by Captain-Of-Coit** [comment]
Can you check if the `HookUI` directory exists inside `~UI~`? And if it does, try to delete it and re-run the modded game.

**Comment by focuszero1** [comment]
when i do that, it now is just a black screen on startup after launcher and I get this: 
![image](https://github.com/Captain-Of-Coit/hookui/assets/152710390/7c6ec7c6-b405-4bda-a6c2-180b0c8a22d2)

**Comment by focuszero1** [comment]
i may have messed that up. deleted the UI folder and not just hookui. ill redownload and try again. my bad
don't worry about that last message
