### ISSUE TITLE
1.0.14f1 compatibility

### ISSUE THREAD

**Issue by HexHyte** [Captain-Of-Coit/hookui#8]
The latest update has caused the mod to stop working due to compatibility issues.

**Comment by Captain-Of-Coit** [comment]
Note to self, new JS bundle has sha256sum `CAA2852C609B391E942A474EA4A26A4AD14E66DE6A1C5FEE4E1B8C111D3E9492`, compared to initial version `b9bffb759486ac99875974778c0a52fb44fcb973c1055c002c2e14ec2935f5cd`

**Comment by CaptPungent** [comment]
Thank you, Captain-Of-Coit. Horses held.

**Comment by Captain-Of-Coit** [comment]
Thanks to [adamdewolf](https://github.com/adamdewolf), we can now close this :) Latest downloads found over at "Releases": https://github.com/Captain-Of-Coit/hookui/releases
